// <auto-generated />
using System;
using CGI.LeadTracker.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CGI.LeadTracker.Infrastructure.Migrations
{
    [DbContext(typeof(LeadTrackerContext))]
    partial class LeadTrackerContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.17")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("CGI.LeadTracker.Domain.AggregatesModel.Lead.ConversionEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)");

                    b.Property<decimal?>("ContractValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<string>("EventName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("ExternalEventId")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<Guid>("LeadId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Stage")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("LeadId", "Platform", "Stage", "Status");

                    b.ToTable("ConversionEvents", (string)null);
                });

            modelBuilder.Entity("CGI.LeadTracker.Domain.AggregatesModel.Lead.Lead", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)");

                    b.Property<decimal?>("ContractValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CurrentStage")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("RdStationId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("RdStationId")
                        .IsUnique();

                    b.ToTable("Leads", (string)null);
                });

            modelBuilder.Entity("CGI.LeadTracker.Domain.AggregatesModel.User.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("CGI.LeadTracker.Domain.AggregatesModel.Lead.ConversionEvent", b =>
                {
                    b.HasOne("CGI.LeadTracker.Domain.AggregatesModel.Lead.Lead", null)
                        .WithMany("ConversionEvents")
                        .HasForeignKey("LeadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CGI.LeadTracker.Domain.AggregatesModel.Lead.Lead", b =>
                {
                    b.OwnsOne("CGI.LeadTracker.Domain.AggregatesModel.Lead.LeadIdentifier", "Identifier", b1 =>
                        {
                            b1.Property<Guid>("LeadId")
                                .HasColumnType("char(36)");

                            b1.Property<string>("Type")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("varchar(50)")
                                .HasColumnName("IdentifierType");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("varchar(500)")
                                .HasColumnName("IdentifierValue");

                            b1.HasKey("LeadId");

                            b1.HasIndex("Type", "Value")
                                .IsUnique();

                            b1.ToTable("Leads");

                            b1.WithOwner()
                                .HasForeignKey("LeadId");
                        });

                    b.OwnsOne("CGI.LeadTracker.Domain.AggregatesModel.Lead.PersonalData", "PersonalData", b1 =>
                        {
                            b1.Property<Guid>("LeadId")
                                .HasColumnType("char(36)");

                            b1.Property<string>("Cpf")
                                .HasMaxLength(20)
                                .HasColumnType("varchar(20)")
                                .HasColumnName("Cpf");

                            b1.Property<string>("Email")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("varchar(200)")
                                .HasColumnName("Email");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("varchar(200)")
                                .HasColumnName("Name");

                            b1.Property<string>("Phone")
                                .HasMaxLength(30)
                                .HasColumnType("varchar(30)")
                                .HasColumnName("Phone");

                            b1.HasKey("LeadId");

                            b1.ToTable("Leads");

                            b1.WithOwner()
                                .HasForeignKey("LeadId");
                        });

                    b.Navigation("Identifier")
                        .IsRequired();

                    b.Navigation("PersonalData")
                        .IsRequired();
                });

            modelBuilder.Entity("CGI.LeadTracker.Domain.AggregatesModel.Lead.Lead", b =>
                {
                    b.Navigation("ConversionEvents");
                });
#pragma warning restore 612, 618
        }
    }
}
